//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDBEntities : DbContext
    {
        public PortfolioDBEntities()
            : base("name=PortfolioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PotCategory> PotCategories { get; set; }
        public virtual DbSet<PotColor> PotColors { get; set; }
        public virtual DbSet<PotPlant> PotPlants { get; set; }
        public virtual DbSet<PotPrice> PotPrices { get; set; }
        public virtual DbSet<PotSize> PotSizes { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductColor> ProductColors { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RandomUser> RandomUsers { get; set; }
        public virtual DbSet<UserImage> UserImages { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
