//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandomUser
    {
        public int Id { get; set; }
        public string Gender { get; set; }
        public int GenderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string TimeZone { get; set; }
        public string Email { get; set; }
        public string UniqeID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string MDPassword { get; set; }
        public string LoginSHA { get; set; }
        public string SHAPassword { get; set; }
        public System.DateTime DOB { get; set; }
        public int Age { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int RegisteredAge { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string ImageURL { get; set; }
        public string Nationality { get; set; }
    }
}
