//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int ImageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Label { get; set; }
        public Nullable<int> Size { get; set; }
        public string Url { get; set; }
        public string MimeType { get; set; }
        public byte[] BinaryData { get; set; }
        public byte[] ImageData { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    }
}
